### ISSUE TITLE
[Instrumentation] Check My Bug Fixing

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#124]
hi @lylytran 

I think you introduce new bug when adding new function. Please check my commit 49d0b1ef7f9dd35c30f2308cfda56c1f81629099 to see whether my fix is ok. Many thanks!

**Comment by lylytran** [comment]
Thanks, it's my copy paste bug, I update a little bit at 1635721

**Comment by llmhyy** [comment]
done
