### ISSUE TITLE
[Mutation] Incorrect SRC Source Folder

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#137]
hi @lylytran 

I observe a bug when recovering the mutation regression. When you mutate a class (in Math, e.g., `E:\linyun\software\eclipse-java-mars\eclipse-java-mars-clean\eclipse\trace\mutation\apache-common-math-2.2\FDistributionTest\testCumulativeProbabilityExtremes\org.apache.commons.math.TestUtils_64_9_1\TestUtils.java`) in test folder, your code will recognize the SRC source folder same as the TEST source folder. Please check line 64 of `microbat.mutation.trace.handlers.RunSingleMutationHandler` class.  Thanks!

**Comment by lylytran** [comment]
actually, classes like TestUtils in test source folder is not supposed to be mutated, so I commit the fix for the mutation filter instead.

**Comment by llmhyy** [comment]
thanks, the solution is ok for now
