### ISSUE TITLE
[Report] Trace Length that We Cannot Analyze For Now

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#158]
hi @lylytran 

Would you please generate a new report based on the following report so that we can know how long does the traces that we cannot analyze.

[defects4j0.old.xlsx](https://github.com/llmhyy/microbat/files/1993977/defects4j0.old.xlsx)

**Comment by lylytran** [comment]
Hi Lin Yun, 
This is the report for those cases, you can find trace length at columns in red.
[Agent_Defect4j0_filter.xlsx](https://github.com/llmhyy/microbat/files/1994348/Agent_Defect4j0_filter.xlsx)

**Comment by llmhyy** [comment]
hi @lylytran 

Many thanks for your report! However, some traces have 105001 steps, which indicates that their real trace length could be even larger. Would you please set the step_limit to -1 (indicating we will trace as much as we can) and generate the report again? Many thanks!

**Comment by lylytran** [comment]
Hi Lin Yun,
The updated report:
[Agent_Defect4j0.xlsx](https://github.com/llmhyy/microbat/files/1999480/Agent_Defect4j0.xlsx)

**Comment by lylytran** [comment]
Updated report:
[Agent_Defect4j0.xlsx](https://github.com/llmhyy/microbat/files/1999951/Agent_Defect4j0.xlsx)

**Comment by llmhyy** [comment]
great job!
