### ISSUE TITLE
Missing data flow and control flow

### ISSUE THREAD

**Issue by SongXueZhi** [llmhyy/microbat#194]
Microbat will lose data flow and control flow during the debug process. For example:
e.g. stack.push(j), stack.get(j). 
The get() method does not regard push() method as inducement.

**Comment by SongXueZhi** [comment]
The test case to produce the issue is here [microbat_experiment#2](https://github.com/llmhyy/microbat_experiment/issues/2)

**Comment by llmhyy** [comment]
I leave some code, please read and follow the clue to finish the rest
