### ISSUE TITLE
Parse Regular Expression for Allowed Library Class

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#36]
Suppose we need to allow Microbat to analyze the java classes under java.awt.event package, we should allow user to customize such a restriction in preference page.

For the current implementation, JPDA only allows us to use * to describe excluded library. For example, when feeding a regular expression like java.* as excluded class pattern to JPDA, it will omit all the classes with its name starting with "java.". Therefore, if we want additional library class such as java.awt.event.*.java, we need to list all the string patterns except java.awt.event.*.java, for example, java.awt.A*, java.awt.B*, .... Hence, when user input java.awt.event.* in the preference page, we to automatically transfer it into a list of class patterns except java.awt.event.*.

**Comment by lylytran** [comment]
4ead024

**Comment by llmhyy** [comment]
@lylytran 

I checked your implementation, it seems that you cannot rely IJavaProject to achieve the packages, instead, you may access `Activator.getDefault().getPreferenceStore().getString(JAVA7HOME_PATH)`. In addition, I may need more of your instruction on how to use your implemented functions.

**Comment by llmhyy** [comment]
The function seems to be incorrect as well. :(

**Comment by llmhyy** [comment]
done
